version: '2'
services:
    msstools-app:
        image: msstools
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://msstools-postgresql:5432/msstools
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    msstools-postgresql:
        extends:
            file: postgresql.yml
            service: msstools-postgresql
